// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=dreamseat-75ed1
// to regenerate.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Firebase project: dreamseat-75ed1
/// Sender ID / project number: 194348582720
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // macOS uses the same config as iOS when configured
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── WEB ─────────────────────────────────────────────────────────────────
  // App ID: 1:194348582720:web:834e32bd7a4b0af87adca5
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCrPxDfL6fnXmJCuefqUYCAfPOzV8S5E',
    appId: '1:194348582720:web:834e32bd7a4b0af87adca5',
    messagingSenderId: '194348582720',
    projectId: 'dreamseat-75ed1',
    authDomain: 'dreamseat-75ed1.firebaseapp.com',
    storageBucket: 'dreamseat-75ed1.firebasestorage.app',
    measurementId: 'G-E6K835V3RP',
  );

  // ─── ANDROID ─────────────────────────────────────────────────────────────
  // App ID: 1:194348582720:android:d3222df5965f6a7c7adca5
  // google-services.json is auto-generated by flutterfire configure at android/app/
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeF9FN6BCXGQvRMSHU8cHwehz1mwzKWHY',
    appId: '1:194348582720:android:d3222df5965f6a7c7adca5',
    messagingSenderId: '194348582720',
    projectId: 'dreamseat-75ed1',
    storageBucket: 'dreamseat-75ed1.firebasestorage.app',
  );

  // ─── iOS ─────────────────────────────────────────────────────────────────
  // App ID: 1:194348582720:ios:e7e3fa6326448c007adca5
  // Bundle ID: com.dreameats.dreameats
  // GoogleService-Info.plist auto-generated at ios/Runner/GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnr9pfyEjIlKz5jQpe5NNy-OAPcEvYM3M',
    appId: '1:194348582720:ios:e7e3fa6326448c007adca5',
    messagingSenderId: '194348582720',
    projectId: 'dreamseat-75ed1',
    storageBucket: 'dreamseat-75ed1.firebasestorage.app',
    iosBundleId: 'com.dreameats.dreameats',
  );
}
